eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    hostname: 127.0.0.1

server:
  port: 8090

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

  application:
    name: eureka-client
